### ISSUE TITLE
Server Configuration is not stored in SaveGames folder

### ISSUE THREAD

**Issue by markusressel** [YannickFricke/Satisfactory-DS-Docker#2]
Hi there,

really awesome repo and container, using it since yesterday and it "just works" :nerd_face: 
One thing I wanted to mention though:

When only persisting the `/home/steam/.config/Epic/FactoryGame/Saved/SaveGames/server` folder, savegames are saved, but the server configuration itself (like the password and session etc.) is not.

To fix this I simply "extended" the things that are persisted to the following two locations:
- `/home/steam/.config/Epic/FactoryGame/Saved`
- `/home/steam/Steam/SatisfactoryDedicatedServer/FactoryGame/Saved`

Hope this helps someone :)

**Comment by YannickFricke** [comment]
Hey Markus,
thanks for the kind words!

Ye this is sadly due how the gameserver and Docker works...
The configuration files are only created by SteamCMD when you validate or install the gameserver, after this point the gameserver doesn't create the configuration files when they are missing...
So mounting an empty directory doesn't work out in that case due to Docker does not preserve the files which were stored at the location.

A better possibility would be if we replace the configuration values at startup due to environment variables - then it would be far easier to set up a Kubernetes cluster with this image.

Of course there is the temporary solution that someone copies the configuration files out of the container, puts them into a separate directory and mounts that into the container again.

Would be nice if someone could make a PR since I don't have proper internet for about 2 weeks! :)

**Comment by markusressel** [comment]
Interesting, I have not copied anything from the container, but it seems to work fine nonetheless.
This is the deployment I use (more or less):

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: deployment-satisfactory
  name: satisfactory
  namespace: gameservers
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: deployment-satisfactory
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deployment-satisfactory
    spec:
      nodeName: kfc
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: yfricke/satisfactory-server:latest
        name: satisfactory
        command: ["/bin/sh"]
        args:
          - "-c"
          - "mkdir -p /home/steam/.config/Epic/FactoryGame;      ln -sf /home/steam/savegames /home/steam/.config/Epic/FactoryGame/Saved       ; ln -sf /home/steam/data /home/steam/Steam/SatisfactoryDedicatedServer/FactoryGame/Saved       ; /home/steam/Steam/SatisfactoryDedicatedServer/FactoryServer.sh -multihome=0.0.0.0"
        ports:
          - containerPort: 15777
            protocol: UDP
          - containerPort: 15000
            protocol: UDP
          - containerPort: 7777
            protocol: UDP

        volumeMounts:
          # mounted to /home/steam/.config/Epic/FactoryGame/Saved
          - mountPath: /home/steam/savegames
            name: data
            subPath: savegames
          # mounted to /home/steam/Steam/SatisfactoryDedicatedServer/FactoryGame/Saved
          - mountPath: /home/steam/data 
            name: data
            subPath: config
            
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        tty: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: satisfactory-data
```

Due to problems with the owner and group of the _parent_ folder of mounted directories (its a known issue) I resorted to mounting my volume to the home directory and symlinking the original target locations, instead of directly mounting the volume to the desired target location.

Althogh this is a workaround for my permissions problem, it is able to store the server configuration just fine.
